# Generated by Django 4.2.2 on 2023-07-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_building_cust_use_alter_building_over_head_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='add_state',
            field=models.CharField(choices=[('AR', 'Arkansas'), ('MO', 'Missouri'), ('OK', 'Oklahoma')], max_length=2, verbose_name='State'),
        ),
    ]
