# Generated by Django 3.2.12 on 2023-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_customer_notes_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='barn_type',
            field=models.CharField(blank=True, choices=[('House', 'House'), ('Personal Shop', 'Personal Shop'), ('Barn', 'Barn'), ('Shed', 'Shed'), ('Commercial Building', 'Commercial Building'), ('Garage', 'Garage')], max_length=20, null=True, verbose_name='Desired Structure Usuage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='first_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
