# Generated by Django 3.2.12 on 2023-07-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20230729_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
